### PR TITLE
Create Notification Channel in MainActivity.kt

### PR DESCRIPTION
**Pull request by akassab**
- Creates a notification channel in MainActivity.kt
- Assumes we will only operate on API 26+

### CODE REVIEW

**Review by aaronchlam — APPROVED** [review]

**Review by SPahooja — DISMISSED** [review]
what does it really do?  If you could share some sort of visual cue or explanation of the effect

**Comment by akassab** [comment]
> what does it really do?  If you could share some sort of visual cue or explanation of the effect


https://developer.android.com/training/notify-user/channels

**Comment by SPahooja** [comment]
> > what does it really do?  If you could share some sort of visual cue or explanation of the effect
> 
> https://developer.android.com/training/notify-user/channels

it would be useful if you could send a notification as well

**Comment by akassab** [comment]
> > > what does it really do?  If you could share some sort of visual cue or explanation of the effect
> 
> > 
> 
> > https://developer.android.com/training/notify-user/channels
> 
> 
> 
> it would be useful if you could send a notification as well

Keeping prs smaller is more effective imo

**Pull request merged**
